In [9]:
'''
Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.
'''


import numpy as np
   
def vander_matrix(ipvector, n, increasing=False):
    if not increasing:
        matrix = np.array([x**(n-1-i) for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    elif increasing:
        matrix = np.array([x**i for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    
    return matrix

inputvector = np.array([1,2,3,4,5])
col = 4
matrix_inc_order = vander_matrix(inputvector,col,True)
matrix_dec_order = vander_matrix(inputvector,col,False)

print("Input array :-",inputvector,"\n")
print("Number of columns in output matrix :-",no_col_opmat,"\n")
print("Alexandre-Theophile Vandermonde matrix of the input array in decreasing order of powers:\n\n",matrix_inc_order,"\n")
print("Alexandre-Theophile Vandermonde matrix of the input array in increasing order of powers:\n\n",matrix_dec_order,"\n")

inputvector = np.array([10,9,8,7,6,5,4,3,2,1])
col = 6
matrix_inc_order = vander_matrix(inputvector,col,True)
matrix_dec_order = vander_matrix(inputvector,col,False)

print("Input array :-",inputvector,"\n")
print("Number of columns in output matrix :-",no_col_opmat,"\n")
print("Alexandre-Theophile Vandermonde matrix of the input array in decreasing order of powers:\n\n",matrix_inc_order,"\n")
print("Alexandre-Theophile Vandermonde matrix of the input array in increasing order of powers:\n\n",matrix_dec_order,"\n")

Input array :- [1 2 3 4 5] 

Number of columns in output matrix :- 6 

Alexandre-Theophile Vandermonde matrix of the input array in decreasing order of powers:

 [[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   4  16  64]
 [  1   5  25 125]] 

Alexandre-Theophile Vandermonde matrix of the input array in increasing order of powers:

 [[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]] 

Input array :- [10  9  8  7  6  5  4  3  2  1] 

Number of columns in output matrix :- 6 

Alexandre-Theophile Vandermonde matrix of the input array in decreasing order of powers:

 [[     1     10    100   1000  10000 100000]
 [     1      9     81    729   6561  59049]
 [     1      8     64    512   4096  32768]
 [     1      7     49    343   2401  16807]
 [     1      6     36    216   1296   7776]
 [     1      5     25    125    625   3125]
 [     1      4     16     64    256   1024]
 [     1      3      9     27     81    243]
 [     1 

In [28]:
'''
Problem Statement 2:
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below
i 1 2 3 4 5 6 7 8 9 10
===== == == == == == == == == == ==
Input 10 20 30 40 50 60 70 80 90 100
y1 25 = (10+20+30+40)/4
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4
y6 75 = (60+70+80+90)/4
y7 85 = (70+80+90+100)/4
Thus, the moving average sequence has n-k+1=10-4+1=7 values.
'''

def average(input,n,k):
    loop = n-k+1
    div = k
    j = 0
    for i in range(0,loop):
        sum = 0
        for x in range(j,k):
            sum = sum + input[x]
        avg = sum/div
        print(avg)
        j = j+1
        k = k+1
        
print("-----------------------OUTPUT----------------------------")        
input = [10,20,30,40,50,60,70,80,90,100]
n = len(input)
k = 3
average(input,n,k)
print("The moving average sequence has %s values." %(n-k+1))

print("---------------------------------------------------------")
input = [100,200,300,400,500,600]
n = len(input)
k = 3
average(input,n,k)
print("The moving average sequence has %s values." %(n-k+1))

-----------------------OUTPUT----------------------------
20.0
30.0
40.0
50.0
60.0
70.0
80.0
90.0
The moving average sequence has 8 values.
---------------------------------------------------------
200.0
300.0
400.0
500.0
The moving average sequence has 4 values.


In [29]:
'''
Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.
'''

def average(input,n,k):
    loop = n-k+1
    div = k
    j = 0
    for i in range(0,loop):
        sum = 0
        for x in range(j,k):
            sum = sum + input[x]
        avg = sum/div
        print(avg)
        j = j+1
        k = k+1
        
print("-----------------------OUTPUT----------------------------")        
input = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
n = len(input)
k = 3
average(input,n,k)
print("The moving average sequence has %s values." %(n-k+1))

-----------------------OUTPUT----------------------------
5.0
4.666666666666667
5.666666666666667
6.666666666666667
9.666666666666666
28.666666666666668
49.333333333333336
72.66666666666667
84.0
93.33333333333333
116.33333333333333
The moving average sequence has 11 values.
